version: '3.2'

services:
  # Webserver
  ilias: &ilias
    image: sturai/ilias
    ports:
      - 8080:80
    networks:
      - ilias-net
    depends_on:
      - mysql
    volumes:
      - type: volume
        source: ilias-data
        target: /var/www/html/data
      - type: volume
        source: ilias-iliasdata
        target: /var/iliasdata/ilias
    environment:
      - ILIAS_AUTO_SETUP=1
      - ILIAS_DB_HOST=mysql
      - ILIAS_DB_NAME=ilias
      - ILIAS_DB_USER=ilias
      - ILIAS_DB_PASSWORD=ilias
      - ILIAS_ROOT_PASSWORD=root
      - ILIAS_SETUP_PASSWORD=root
      - ILIAS_CLIENT_NAME=default

  # Cron
  cron:
    # Reuse configuration from webserver
    <<: *ilias
    # Reset ports to avoid conflict with service 'ilias'
    ports: []
    command: cron -f

  # ilServer
  ilserver:
    image: sturai/ilias-ilserver
    networks:
      - ilias-net
    depends_on:
      - ilias
    volumes:
      - type: volume
        source: ilias-lucenedata
        target: /var/lucenedata/ilias
      - type: volume
        source: ilias-data
        target: /app/data
        read_only: true
      - type: volume
        source: ilias-iliasdata
        target: /app/iliasdata
        read_only: true

  # MySQL
  mysql:
    image: mysql:5.7
    command: |
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    networks:
      - ilias-net
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ilias
      - MYSQL_USER=ilias
      - MYSQL_PASSWORD=ilias

volumes:
  ilias-data:
  ilias-iliasdata:
  ilias-lucenedata:
  mysql-data:

networks:
  ilias-net:
